apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.port }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.port }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.port }}
