apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend
      containers:
        - name: backend
          {{- include "backend.imageEnv" . | nindent 10 }}
          ports:
            - containerPort: {{ .Values.port }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.port }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.port }}
