FROM node:22-alpine AS base

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

EXPOSE 3000

FROM base AS dev

COPY . .

CMD ["npm", "run", "dev"]

FROM base AS build

COPY . .
RUN npm run build

FROM node:22-alpine AS prod

WORKDIR /app
ENV NODE_ENV=production

COPY --from=build /app/public ./public
COPY --from=build /app/.next/standalone ./
COPY --from=build /app/.next/static ./.next/static

EXPOSE 3000

CMD ["node", "server.js"]
