name: ""
image: ""
port: 80
env: []
serviceAccount:
  create: false
  name: ""
  annotations: {}
migrate:
  enabled: false
ingress:
  enabled: false
  host: ""
  certificateArn: ""
metrics:
  enabled: false
  path: /metrics
