apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.port }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.port }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.port }}
