apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notification
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: notification
  endpoints:
    - port: http
      path: /metrics
