name: e2e tests

on:
  workflow_dispatch:
  push:
    paths:
      - "e2e/**"
      - "services/frontend/**"
      - "services/backend/**"
      - "docker-compose.e2e.yaml"
  pull_request:
    paths:
      - "e2e/**"
      - "services/frontend/**"
      - "services/backend/**"
      - "docker-compose.e2e.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - run: cp services/backend/.env.example services/backend/.env

      - run: docker compose -f docker-compose.e2e.yaml build backend-e2e frontend-e2e

      - run: docker compose -f docker-compose.e2e.yaml up -d --wait postgres localstack

      - run: docker compose -f docker-compose.e2e.yaml run --rm --entrypoint sh backend-e2e -c "composer install --no-interaction && php artisan key:generate --force && php artisan jwt:secret --force"

      - run: docker compose -f docker-compose.e2e.yaml run --rm frontend-e2e npm ci

      - run: docker compose -f docker-compose.e2e.yaml up -d --wait frontend-e2e backend-e2e

      - run: docker compose -f docker-compose.e2e.yaml exec backend-e2e php artisan db:seed --class=BlogPostSeeder --force

      - run: docker compose -f docker-compose.e2e.yaml run --rm e2e

      - if: failure()
        run: docker compose -f docker-compose.e2e.yaml logs

      - if: always()
        run: docker compose -f docker-compose.e2e.yaml down -v
